### ISSUE TITLE
 lateinit property uiModeDataStore has not been initialized

### ISSUE THREAD

**Issue by superorange** [Spikeysanju/JetQuotes#225]
Run error！

2022-11-16 14:42:04.395 25413-25413/? E/sanju.jetquote: LoadAppImageStartupCache enabled : 1
2022-11-16 14:42:04.482 25413-27799/www.spikeysanju.jetquotes E/BehaviorCollectManager: Fail to acquire dataAnalyzerService...
2022-11-16 14:42:04.777 25413-27824/www.spikeysanju.jetquotes E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@e6f7017
2022-11-16 14:42:04.922 25413-25413/www.spikeysanju.jetquotes E/AndroidRuntime: FATAL EXCEPTION: main
    Process: www.spikeysanju.jetquotes, PID: 25413
    kotlin.UninitializedPropertyAccessException: lateinit property uiModeDataStore has not been initialized
        at www.spikeysanju.jetquotes.view.MainActivity.getUiModeDataStore(MainActivity.kt:53)
        at www.spikeysanju.jetquotes.view.MainActivity$observeUITheme$1.invokeSuspend(MainActivity.kt:86)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:75)
        at androidx.lifecycle.DispatchQueue.resume(DispatchQueue.kt:54)
        at androidx.lifecycle.LifecycleController$observer$1.onStateChanged(LifecycleController.kt:40)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:187)
        at android.app.Activity.dispatchActivityPostStarted(Activity.java:1418)
        at android.app.Activity.performStart(Activity.java:8464)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4319)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2706)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:228)
        at android.app.ActivityThread.main(ActivityThread.java:9105)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:614)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1129)

**Comment by shanurrahmanpenny** [comment]
+ facing the same issue

**Comment by Abdulelahsg** [comment]
Me too.

**Comment by SalihAbdalrahman** [comment]
any suggestion?

**Comment by SalihAbdalrahman** [comment]
i need fix for this problem

**Comment by imrankhalid001** [comment]
Hi! 👋

I’ve fixed the lateinit property uiModeDataStore has not been initialized issue and submitted a PR with several updates to improve compatibility and UI consistency. You can check it out here: [#256](https://github.com/Spikeysanju/JetQuotes/pull/256)
 🚀

🐞 **Bug Fixes**
- Fixed `lateinit property uiModeDataStore has not been initialized` runtime crash
- Resolved TopBar overlap issue under the system status bar on Android 15 (edge-to-edge enforcement)

🔧 Technical Updates

Upgraded Gradle build, Kotlin, and Hilt versions for Android 15 support

Updated Compose compiler and Material dependencies

Optimized project settings for the latest Android SDK

🎨 UI Enhancements

Improved DetailScreen layout and padding using Scaffold

Center-aligned bottom action buttons with proper background styling

✅ Overall Improvements

Enhanced UI consistency across Android versions

Refactored composable structure for better maintainability

Feel free to review and test the updated code — happy to make any adjustments if needed! 😊
